FROM php:8.2-apache

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    zip \
    unzip \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*


#Enable mod_rewrite
RUN a2enmod rewrite

#Copy the application code
COPY . /var/www/html

# Set working directory
WORKDIR /var/www/html


# Install PHP extensions
RUN docker-php-ext-install pdo_mysql zip 

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set permissions
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap
RUN chmod -R 775 /var/www/html/storage /var/www/html/bootstrap

# Install PHP dependencies
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

#Install project dependencies
RUN composer install


